name: Eighth Workflow
on:
  workflow_dispatch:
    inputs:
      titleCustom:
        description: 'Type the title'
        required: true
        type: string
        default: 'Hello World'

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Event Variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
