name: Fifth Workflow
on: [push, issues, pull_request]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Event Variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
