name: First Workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: First Command
        run: echo "Hello, World!"
      - name: Second Command
        run: |
          node -v
          npm -v
