name: Fourth Workflow
on:
  workflow_run:
    workflows: ['Third Workflow']
    types:
      - completed

jobs:
  success-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: List files
        run: echo "Success"
  failure-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: List files
        run: echo "Failure"
