name: Seventh Workflow
on:
  workflow_dispatch

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Event Variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
