name: Six Workflow
on:
  push:
    branches:
      - main
      - 'page/*' # page/about, page/contact, etc.
      - 'page/**' # page/about, page/contact, etc.
      - '!page/blog'
    #tags:
    #  - "v1.*" # v1.1, v1.2, v1.3, etc.
    #  - "!v1.2.1"
    paths:
      - '**.html'

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Event Variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
