name: Tenth Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Context and Expressions
        id: context-expression
        run: |
          echo ${{ toJson(github) }}
          echo ${{ toJson(runner) }}
          echo ${{ toJson(job) }}
          echo ${{ toJson(steps) }}
