name: Third Workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Command in Multiline
        run: echo "Hello, World!"
      - name: Second Command
        run: |
          pwd
          ls -a
